### ISSUE TITLE
[`./bin/test`] Allow skipping clone of `swift-docc` and `swift-docc-render-artifact`

### ISSUE THREAD

**Issue by bitjammer** [apple/swift-docc-plugin#22]
From https://github.com/apple/swift-docc-plugin/pull/21#discussion_r929419898

In some scenarios, running swift-docc-plugin tests against the built-in docc in the installed toolchain could save time. Add an option to `./bin/test` to skip cloning `swift-docc` and `swift-docc-render-artifact` and setting the environment variables to use those.

Behavior:

If `--skip-building-upstream-docc` (or perhaps an environment variable) is set:
- Don't set the following:
  - `SWIFT_DOCC_ROOT`
  - `SWIFT_DOCC_RENDER_ARTIFACT_ROOT`
  - `SWIFT_DOCC_BRANCH`
  - `SWIFT_DOCC_RENDER_ARTIFACT_BRANCH`
- Don't clone `swift-docc` or `swift-docc-render-artifact`
- Also don't set:
  - `DOCC_EXEC`
  - `DOCC_HTML_DIR`

See the above mentioned pull request for new code that should be skipped in this case.

**Comment by A-N-uraag** [comment]
Hi @bitjammer, can I work on this? I went through the mentioned PR and I now have a clear idea on what needs to be done.

**Comment by bitjammer** [comment]
Of course, that’s why it’s here! Thank you for taking it on. Please have a go and let me know if you have any questions.

**Comment by A-N-uraag** [comment]
Hi @bitjammer, I raised a PR. I used the approach to use an env variable. Hope that's fine.

**Comment by A-N-uraag** [comment]
Hi @bitjammer, just sending a little nudge to bump up the PR in your inbox. Thanks.

**Comment by bitjammer** [comment]
Thank you! I will have a look at this today.

**Comment by bitjammer** [comment]
Nice work @A-N-uraag, thank you.
