### ISSUE TITLE
Snippet crash: No value associated with key 'chunks'

### ISSUE THREAD

**Issue by kelvin13** [apple/swift-docc-plugin#23]
running a recent revision (`00555b6efa14095243fbce031dba8a03cfc6333e`) of this plugin on [`swift-json`](https://github.com/kelvin13/swift-json/tree/59d34c5f8c337b068d07ad5b0e4caa2fd0b8176e) crashes with 

```
/home/klossy/dev/swift-json/Sources/JSON/JSON.docc/json.md:1:1: warning: Unknown directive 'import'; this element will be ignored
/home/klossy/dev/swift-json/Sources/JSON/JSON.docc/json.md:2:1: warning: Unknown directive 'import'; this element will be ignored
/home/klossy/dev/swift-json/Sources/JSON/JSON.docc/json.md:1:1: warning: An article is expected to start with a top-level heading title
Error: keyNotFound(CodingKeys(stringValue: "chunks", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "symbols", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "snippet", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"chunks\", intValue: nil) (\"chunks\").", underlyingError: nil))

Generating documentation for 'LintingDictionary'...
error: 'docc convert' invocation failed with a nonzero exit code: '1'
error: unspecified("ExitCode(rawValue: 1)")
```

### Checklist
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc-plugin/issues).

### Expected behavior

`swift-json`’s documentation was written for Biome, so i don’t expect this plugin to handle all of its documentation by default, but it should probably ignore the invalid snippets gracefully instead of crashing.

### Actual behavior

already described above.

### Steps to Reproduce

1. clone `swift-json` at `59d34c5f8c337b068d07ad5b0e4caa2fd0b8176e`, and replace its docgen tool with:

```
.package(url: "https://github.com/apple/swift-docc-plugin", revision: "00555b6efa14095243fbce031dba8a03cfc6333e"),
```

2. run `$ swift package generate-documentation`

### Swift-DocC Plugin Version Information

**Swift-DocC plugin version:** `00555b6efa14095243fbce031dba8a03cfc6333e`

```
$ swift --version
Swift version 5.8-dev (LLVM e41a0a126d143ae, Swift 23e5143d22cb768)
Target: x86_64-unknown-linux-gnu
$ swiftenv version
DEVELOPMENT-SNAPSHOT-2022-07-25-a 
```

**Comment by kelvin13** [comment]
here is a minimal project reproducing the crash: https://github.com/kelvin13/swift-snippet-test-crash

i did nothing except generate a default library package with `swift package init` and added an empty snippet containing:

```
// this is a test snippet 
print("hello world")
```

**Comment by ethan-kusters** [comment]
@bitjammer is this something you could look into?

**Comment by bitjammer** [comment]
Yes I can take a look next week. Chunks should not be generated nor expected anywhere at this point as we are using “slices” now—a different data structure.

**Comment by bitjammer** [comment]
Apologies, it might be that the version of DocC that you are using is too old for this version of swift-docc-plugin (and SymbolKit, where this data structure has changed). Not sure why it didn't make it into the 7-25 toolchain, perhaps the toolchain build started in the middle of the night and I landed this change later that day.

You will want to use a version of DocC that is newer than [a4021f1d849813ac198ddfbe941b42f9c61a2bed](https://github.com/apple/swift-docc/commit/a4021f1d849813ac198ddfbe941b42f9c61a2bed), which adopts these changes. It looks like swift-DEVELOPMENT-SNAPSHOT-2022-08-01-a or later should have those changes. @kelvin13 can you give a later toolchain a try please and let me know if that works for you?

**Comment by kelvin13** [comment]
i can confirm the issue no longer exists in `DEVELOPMENT-SNAPSHOT-2022-10-11-a`.
